<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view" class="container"><?php echo $this->getMessagesBlock()->setEscapeMessageFlag(true)->toHtml() ?></div>
<div class="product-view container">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <?php echo $this->getBlockHtml('formkey') ?>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>
        <div class="product-essential row">

            <div class="col-xs-12 col-sm-6 col-md-6">
                <?php echo $this->getChildHtml('media') ?>
            </div>

            <div class="col-xs-12 col-sm-6 col-md-6">
                
                <div class="product-main-info">
                    <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                    
                    <p class="product-ids"><?php echo $this->__('SKU# %s', $this->escapeHtml($_product->getSku())); ?></p>
                    <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
                    <?php echo $this->getChildHtml('alert_urls') ?>

                    <?php if ($_product->getShortDescription()):?>
                        <div class="short-description std">
                            <?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?>
                        </div>
                    <?php endif;?>

                    <?php echo $this->getChildHtml('product_type_data') ?>
                </div>
                <?php echo ($_product->getCanShowPrice() === false) ? '' : $this->getChildHtml('tierprices'); ?>
                <?php echo $this->getChildHtml('extrahint') ?>

                <?php if (!$this->hasOptions()):?>
                    <div class="add-to-box">
                        <?php if($_product->isSaleable()): ?>
                            <?php echo $this->getChildHtml('addtocart') ?>
                        <?php endif; ?>
                        <?php echo $this->getChildHtml('addto') ?>
                    </div>
                <?php else:?>
                    <?php if ($_product->isSaleable() && $this->hasOptions() && $this->getChildChildHtml('container1') ):?>
                        <div class="options-container-small">
                            <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                        </div>
                    <?php else: ?>
                        <?php echo $this->getChildHtml('addto') ?>
                    <?php endif;?>
                <?php endif; ?>

                <?php if ($_product->isSaleable() && $this->hasOptions() && $this->getChildChildHtml('container2') ):?>
                    <div class="options-container-big">
                        <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                    </div>
                <?php endif;?>

                <?php if ($this->canEmailToFriend()): ?>
                    <div class="a-right">
                        <a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>" class="btn btn-primary btn-sm"><span class="glyphicon glyphicon-envelope mr-3"></span><?php echo $this->__('Email to a Friend') ?></a>
                    </div>
                <?php endif; ?>

                <?php echo $this->getChildHtml('other');?>
            </div>

        </div>
        <div class="clearfix">&nbsp;</div>
        <div>
            <?php if ($detailedInfoGroup = $this->getChildGroup('detailed_info', 'getChildHtml')):?>
                <dl id="collateral-tabs" class="collateral-tabs">
                <?php foreach ($detailedInfoGroup as $alias => $html):?>
                    <dt class="tab"><span><?php echo $this->escapeHtml($this->getChildData($alias, 'title')) ?></span></dt>
                    <dd class="tab-container">
                       <div class="tab-content"><?php echo $html ?></div>
                    </dd>
                <?php endforeach;?>
                </dl>
                <script type="text/javascript">
                //<![CDATA[
                    var collateralTabs = new Enterprise.Tabs('collateral-tabs');
                    Event.observe(window, 'load', function() {
                        collateralTabs.select();
                    });
                //]]>
                </script>
            <?php endif; ?>
        </div>
        <div class="clearfix">&nbsp;</div>
        
    </form>
        <?php echo $this->getChildHtml('relatedProducts') ?>
        <?php echo $this->getChildHtml('upsell_products') ?>
        <?php echo $this->getChildHtml('productTagList') ?>
        <?php echo $this->getChildHtml('product_additional_data') ?>
</div>

<script type="text/javascript">
//<![CDATA[
    var productAddToCartForm = new VarienForm('product_addtocart_form');
    productAddToCartForm.submit = function(button, url) {
        if (this.validator.validate()) {
            var form = this.form;
            var oldUrl = form.action;

            if (url) {
               form.action = url;
            }
            var e = null;
            try {
                this.form.submit();
            } catch (e) {
            }
            this.form.action = oldUrl;
            if (e) {
                throw e;
            }

            if (button && button != 'undefined') {
                button.disabled = true;
            }
        }
    }.bind(productAddToCartForm);

    productAddToCartForm.submitLight = function(button, url){
        if(this.validator) {
            var nv = Validation.methods;
            delete Validation.methods['required-entry'];
            delete Validation.methods['validate-one-required'];
            delete Validation.methods['validate-one-required-by-name'];
            // Remove custom datetime validators
            for (var methodName in Validation.methods) {
                if (methodName.match(/^validate-datetime-.*/i)) {
                    delete Validation.methods[methodName];
                }
            }

            if (this.validator.validate()) {
                if (url) {
                    this.form.action = url;
                }
                this.form.submit();
            }
            Object.extend(Validation.methods, nv);
        }
    }.bind(productAddToCartForm);
//]]>
</script>
