<?php /** @var $this RedLightBlinking_ProductSlider_Block_Widget */ ?>
<?php $products = $this->getProducts() ?>
<?php if(count($products)): ?>
<?php $_helper = $this->helper('catalog/output'); ?>
<div class="product-slider" id="<?php echo $this->getSliderId() ?>">
	<div class="title">
		<h3><?php echo $this->escapeHtml($this->getTitle()) ?></h3>
	</div>
	<div class="a-right">
		<div class="btn-group control">
			<a href="javascript:void(0);" class="btn btn-default btn-sm prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
			<a href="javascript:void(0);" class="btn btn-default btn-sm next"><span class="glyphicon glyphicon-chevron-right"></span></a>
		</div>
	</div>
	
	<ul class="products">
		<?php foreach($products as $_product): ?>
			<li>
				<a href="<?php echo $_product->getProductUrl() ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(200); ?>" class="img-thumbnail" /></a>
				<h5 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h5>
				<?php // echo $this->getPriceHtml($_product, true) ?>
				<div class="actions">
					<?php if($_product->isSaleable()): ?>
						<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-success" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
					<?php else: ?>
						<?php if ($_product->getIsSalable()): ?>
							<p class="availability in-stock"><span><?php echo $this->__('In stock') ?></span></p>
						<?php else: ?>
							<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
						<?php endif; ?>
					<?php endif; ?>
					<ul class="add-to-links">
						<?php if ($this->helper('wishlist')->isAllow()) : ?>
							<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist btn btn-link"><span class="glyphicon glyphicon-heart"></span><?php echo $this->__('Add to Wishlist') ?></a></li>
						<?php endif; ?>
					</ul>
				</div>
			</li>
		<?php endforeach ?>
	</ul>
</div>
<?php endif ?>
<?php echo $this->getSliderJs() ?>
