<div class="header-panel">
    <div class="switches"><?php //echo $this->getChildHtml('switches') ?>

	<div class="checkout-link">
		<?php echo $this->getChildHtml('topCart') ?>
	</div>
	
	<span class="glyphicon glyphicon-user"></span>
	<?php echo $this->getChildHtml('topLinks') ?>
    </div>
    <p class="welcome-msg"><?php echo $this->getChildHtml('welcome') ?></p>
    <?php echo $this->getChildHtml('accountLinks') ?>
</div>
<div class="header">
    <div class="branding">
    <?php if ($this->getIsHomePage()):?>
	<h1 class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
	<?php else:?>
	<a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
	<?php endif?>
	<?php echo $this->getChildHtml('headerCallout') ?>
    </div>

    <?php echo $this->getChildHtml('topSearch') ?>

</div>
<?php echo $this->getChildHtml('topMenu') ?>
<?php echo $this->getChildHtml('topContainer') ?>
